packages:
  - templates/*
  - landing
  - packages/*
  - packages/ui-adapters/*
  - guides/*
ignoredBuiltDependencies:
  - chromedriver
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - sharp
  - unrs-resolver
